### PR TITLE
feat: python script to dynamically generate population default scenarios for each region.

### PR DESCRIPTION
**Pull request by nnoll**
This is a WIP branch that restructures how we input default scenarios into the app that should be more flexible than the current version. I've introduced a python script "scripts/collect_scenario_initial_conditions.py" that will collect a global json file that holds all form values that should be filled in for each scenario by default"

This is part of a larger change that should simplify the app which will allow for one global toggle of scenarios.

### CODE REVIEW

**Comment by nnoll** [comment]
OK, I think this feature can be merged with master as it doesn't change anything about the current workflow. Objections?

**Comment by rneher** [comment]
I adjusted this branch to match the pattern now implemented in master. The scenarios are generated by the call 
```
python covid19_scenarios_data/parse_all.py --output-scenarios covid19_scenarios/src/assets/data/scenarios/scenarios.json
```

**Comment by noleti** [comment]
At some point, `parse_all.py` might need to be renamed to `generate_data.py` or similar?

**Comment by nnoll** [comment]
@noleti I agree, I changed it to `generate_case_counts.py` to be specific. I also removed parse_all.sh since it has been deprecated for awhile and it's confusing which one we use for a new contributor. If there are no objections, I'll merge this now

**Pull request merged**
