### PR TITLE
Fix bug with latest latest data for France not being processed

### PR DESCRIPTION
**Pull request by Christian-G-UT**
Starting with the last 5 days French regional data no longer reports number of confirmed cases, only hospitalized, ICU and deaths. Due to the coding that ignored data when confirmed cased was "None" French regional data no longer appeared for the last days. Bug fixed so data now goes all the way to the last day but I havn't checked whether having "None" for the confimed cases would cause any other bug elsewhere.

### CODE REVIEW

**Comment by noleti** [comment]
We should in general tolerate None values, but data series should also be cumulative. That means, if none-zero values were reported in the past, the parser should not send None values for future dates. If this is currently the case, I would recommend to sort the dates, and then fill the gaps with last known cumulative values. Have a look at line 64 onwards from the ecdc parser for reference (that one additionally aggregates, which you don't need). Can you also make sure to resolve conflicts in the PR? Thanks!

**Comment by Christian-G-UT** [comment]
I am afraid there will not be any reporting of confirmed cases on a regional level for France anytime soon. This is because of scarce testing, a change in testing policy and the fact that the policies are not consistent between regions. So I think for the next weeks/months we will not see any confirmed cases in the dataset (only hospitalized, ICU and deaths). Do you still recommend to fill out the confirmed cases with the last known value?

**Comment by noleti** [comment]
That's a good point. @rneher can you comment? Should the cumulative count be None if continued reporting of None values can be expected (after initial values were provided)?

**Comment by rneher** [comment]
yes, I would report None in this case. We check this when plotting.

**Pull request merged**
