### PR TITLE
🇫🇷 Add data parser for France

### PR DESCRIPTION
**Pull request by aschelch**
Hi,

I added a parser for the data gathered the repo 
https://github.com/opencovid19-fr/data

I also generated to .tsv files.

### CODE REVIEW

**Comment by rneher** [comment]
Thank you so much, this is fantastic. Do you happen to have the information on population sizes of the different regions? And maybe hospital beds? In order to include the regions are population presets, we would need these numbers as entries in analogy to these from 

https://github.com/neherlab/covid19_scenarios_data/blob/master/populationData.tsv#L76

If exact info are available on hospital beds, we have used scaled averages of the national total. Same for suspected case counts on March 1st (current cases divided by 30 would probably do as a guess.).

**Comment by rneher** [comment]
@aschelch could you get hold of these numbers? They don't need to be exact. Estimates are better than nothing at this stage.

**Comment by aschelch** [comment]
I'm trying to get those. I will come back to you ASAP.

**Comment by aschelch** [comment]
I added data I found using 👍 

- https://www.lefigaro.fr/lits-en-reanimation-une-repartition-tres-inegale-qui-rend-indispensable-les-transferts-20200318
- https://www.lefigaro.fr/lits-en-reanimation-une-repartition-tres-inegale-qui-rend-indispensable-les-transferts-20200318
- http://www.snmrhp.org/Data/upload/images/1Copie%20de%20Enqute%20Ra-respirateurs%20juin%2009%20(S%20Mouton%2014%20aot%2009).pdf

Hope I did right ;)

**Comment by aschelch** [comment]
Im not sure about the `importsPerDay` data. What do you mean by imports ? 
Number of new case having COVID ?

**Comment by nnoll** [comment]
Imports would be the number of new cases brought in by travelers into the region. It appears you've set this to 1 for all regions. If you're OK with this, I'll test this branch to see if it works and if so merge it.

**Comment by rneher** [comment]
Excellent. Thanks a lot.

**Comment by aschelch** [comment]
@nnoll I put 1 by default. How can you know this data ?

**Pull request merged**
