### PR TITLE
🇳🇱 feat: add icu data for netherlands

### PR DESCRIPTION
**Pull request by hongaar**
Added data source for ICU cases for The Netherlands from Stichting NICE: https://www.stichting-nice.nl/. They don't mention any license for the data, this is the description from their website (translated with Google):

> Since the COVID-19 outbreak at the end of February, the Dutch ICs have registered these in the NICE registration. These data will be linked at a later stage to the regular NICE data regarding, among other things, disease severity, demographics, mortality and treatment duration. Below is an overview of the number of (current) recordings with a COVID-19 infection on the Dutch ICs. For the compilation of this overview, we depend on data delivery by the participating ICs. Due to pressure on the IC, there may be a delay of 2 to 3 days in the data delivery.

My knowledge of Python is very limited. Open to hear how I can improve the script.

### CODE REVIEW

**Comment by hongaar** [comment]
I can also look into adding Dutch provinces based on https://github.com/J535D165/CoronaWatchNL.

PS: They have a CI job setup to download and parse data every hour: https://github.com/J535D165/CoronaWatchNL/blob/master/.github/workflows/download.yml
I can adapt it for this repo if that's useful?

**Comment by nnoll** [comment]
@hongaar: This looks great -- thank you so much! Would you mind filling out an entry for the Netherlands within populationData.tsv? Without this, the case counts you have kindly provided us won't be loaded as a seperate scenario. Once I have this I'll accept the pull request.

Regarding your second point -- if you can provide provinces that would be great! And we have talked about adding a bot that can pull new data if it's available for this repo for a bit now. If you want to have a go at it, that would be awesome!

**Comment by rneher** [comment]
We would ideally have cases, deaths, and ICU in one file. The file you currently output only writes ICU patients to file. Is there a comparable source for the other fields? Otherwise this could be merged with the data aggregated by ECDC

**Comment by hongaar** [comment]
> We would ideally have cases, deaths, and ICU in one file. The file you currently output only writes ICU patients to file. Is there a comparable source for the other fields? Otherwise this could be merged with the data aggregated by ECDC

Yeah I was not sure how to approach this. The source I added only has ICU data. Does it make sense to pull in more (duplicate?) data into the `.tsv` file for The Netherlands, or does the `parse_all` script merge it already?

**Comment by rneher** [comment]
We currently forsee only one `.tsv` file per location. So it would be ideal if we could merge this before generating the `.tsv` and then funnel all of this into the json.

**Comment by hongaar** [comment]
@rneher added separate sources for cases, deaths and hospitalized to `.tsv`.

@nnoll there was already an entry in `populationData.tsv`, should I add anything else? Created #47 for the scheduled job.

**Pull request merged**
