### PR TITLE
🇮🇳 add India state-level data

### PR DESCRIPTION
**Pull request by kupad95**
Hi, I added a parser for Indian state-level COVID-19 data stored here: https://github.com/amodm/api-covid19-in

### CODE REVIEW

**Comment by rneher** [comment]
Thanks so much, this is great! I have three quick suggestions before we merge:
  * In https://github.com/neherlab/covid19_scenarios_data/blob/f79bb12d447361000499ae3a3d2ac453c36753cc/populationData.tsv#L150 and following, could you prefix the India's states by the three letter country code `IND-` rather than `India-`. This way they will be matched up properly
  *  Please increase the `importsPerDay` field to at least `0.1`. If initial cases and imports per day are both zero, the simulation will never get off the ground and stay zero for ever.... This affects lines like https://github.com/neherlab/covid19_scenarios_data/blob/f79bb12d447361000499ae3a3d2ac453c36753cc/populationData.tsv#L165
 * and there is a duplicated line here: https://github.com/neherlab/covid19_scenarios_data/blob/f79bb12d447361000499ae3a3d2ac453c36753cc/populationData.tsv#L148

**Comment by kupad95** [comment]
thanks for the feedback - all three should be fixed now!

**Comment by nnoll** [comment]
All three changes appear to be in order. Thanks for your contribution!

**Comment by noleti** [comment]
I appear to have trouble with the new india parser:

>   File "/home/<redacted>/parsers/india.py", line 48
    for cntry, data in states.items():
                                     ^
IndentationError: unindent does not match any outer indentation level

**Comment by kupad95** [comment]
@noleti an indentation error on that line, but it seems to have been fixed by a commit by @rneher

**Pull request merged**
