### PR TITLE
🇨🇦 Canada parser

### PR DESCRIPTION
**Pull request by noleti**
addresses https://github.com/neherlab/covid19_scenarios_data/issues/36
I added a comment at the source API asking to unify it a bit. If that happens, this parser should break (noisily), and needs to be adapted to the changed API.
Parser adds state and county-level data, hope this is not too detailed. There are some minor quirks such as 'not reported' as county names, which are currently not handled/ treated as county names

The PR contains additional functionality for util, as far as I could tell it should not impact the other parsers (diffing the .json is a bit hard through).

### CODE REVIEW

**Comment by noleti** [comment]
The source was now slightly simplified, parser should be good to use. There is the remaining issue that for states which have only one county (e.g., NWT), the parser creates NWT and NWT-NWT, and both contain the same data. I think this is appropriate though, as no other NWT- are created, and thus the numbers present both the county and state level. I also left the Repatriated as state-level category.

**Comment by nnoll** [comment]
Hey @noleti, this looks great. Thanks again for all your help with data parsing, it's been super helpful.

I think having the individual county level data is not informative at the present as it's too granular and the data is still sparse. As the original request was for provinces, I think we can temporarily remove the output of county level data with the intention of adding it back in if/when the case data becomes more populated.

Would you mind making the change -- if not I'll be happy to do it when I get a free moment. Thanks again!

**Comment by noleti** [comment]
ok, quick fix. Don't have too much time to test now, sorry!

**Comment by nnoll** [comment]
OK, this looks great. Thanks for your contribution.

**Pull request merged**
