### PR TITLE
Revised Tsv and parsing to JSON

### PR DESCRIPTION
**Pull request by noleti**
Related to https://github.com/neherlab/covid19_scenarios_data/issues/63, closing https://github.com/neherlab/covid19_scenarios_data/issues/67.

I split the .tsv generation and .json generation. All parsers are now generating .tsv in the folder hierarchy as proposed by @rneher in https://github.com/neherlab/covid19_scenarios_data/issues/63. To parse the .tsv into `assets/case_counts.json`, use `covid19_scenarios_data/generate_data --output-json foo.json` to generate `assets/case_counts.json` and copy into `foo.json`. (if that is not the intended flow, it should be easy to fix).

While now we have nice and tidy .tsv files, I note that ecdc and cds currently generate  196 and 515 files in their folders, respectively. That might not be what was intended? Please advise. I did not commit case-counts/cds to keep the RP smaller, but ecdc/ is committed for reference.

The actual parser changes are in https://github.com/neherlab/covid19_scenarios_data/pull/68/commits/8b44bd2ca43f21e5bf5b2efc72afca2bc663416f. They directly follow what I sketched in https://github.com/neherlab/covid19_scenarios_data/issues/67. Overall, utils was simplified, and parsers only required minor changes (to prepend country code if required).

The first commit is essentially removing the old .tsv files, and adding the new ones. I hoped git would be smart enough to detect that most files just were renamed/moved, but apparently that was not the case.

### CODE REVIEW

**Comment by rneher** [comment]
Thank you! I like this solution. While these are many files, it will allow for atomic commits and we know exactly what each parser produces. Json are then just derived files from the tsv and we have the tsvs as a single source of truth. @nnoll do you agree?

**Comment by rneher** [comment]
thanks again. I added a few more things aligned with my general idea. jsons are now considered derived files that app bundler can generate using 
```
python3 covid19_scenarios_data/generate_all.py --output-cases filename --output-scenarios filename
```
To update the data, one runs 
```
python3 covid19_scenarios_data/generate_all.py --fetch
```
and commits the tsvs.

Does this make sense?

**Comment by rneher** [comment]
I have excluded `cds` for the time being since it doesn't really add much on top of what we already have from the specific parsers. But I am pretty happy with this structure now.

**Comment by noleti** [comment]
Thanks, looks almost all good to me (I think stoi() in utils should be fixed to translate '' to None, will add a commit for that now). I also agree on commenting out `cds`, and not having the .json in git. I realized that now the order of sources does not matter any more, so ecdc might already set values that we want to set later with a specialized parser. Originally, I had ecdc in sources late to essentially just fill the gaps. Do we care about this?

**Comment by noleti** [comment]
Ok, removed some now outdated code, this is ready to be merged from my perspective.

**Comment by rneher** [comment]
excellent!

**Pull request merged**
